In [115]:
# Import required libraries
import numpy as np
import pandas as pd
import hvplot.pandas
from pathlib import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [116]:
# Read salary data
file_path = Path("Training.csv")
df = pd.read_csv(file_path)

# Display sample data
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  scurring  \
0       0           0             0        0                 0  ...         0   
1       0           0             0        0                 0  ...         0   
2       0           0             0        0                 0  ...         0   
3       0           0             0        0                 0  ...         0   
4       0           0             0        0                 0  ...         0   

   skin_peeling  silver_like_dusting  small_dents_in_nails  \
0             0                    0                     0   
1             0                    0                     0   
2             0                    0                     0   
3             0                    0                     0   
4             0                    0                     0   

   inflammatory_nails  blister  red_sore_around_nose  yellow_crust_ooze  \
0                   0        0                     0                  0   
1                   0        0                     0                  0   
2                   0        0                     0                  0   
3                   0        0                     0                  0   
4                   0        0                     0                  0   

          prognosis  Unnamed: 133  
0  Fungal infection           NaN  
1  Fungal infection           NaN  
2  Fungal infection           NaN  
3  Fungal infection           NaN  
4  Fungal infection           NaN  

[5 rows x 134 columns]

In [117]:
# Copy the DataFrame
df2 = df.copy()

print("Original DataFrame:")
print(df)

print("\nNew DataFrame created from the copy:")
print(df2)

Original DataFrame:
      itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0            

In [118]:
# Drop columns with null values
df = df.dropna(axis=1, how='any')

df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [119]:
# Get the list of column names
column_names = df.columns.tolist()

print("Column names in the dataset:")
for column_name in column_names:
    print(column_name)

Column names in the dataset:
itching
skin_rash
nodal_skin_eruptions
continuous_sneezing
shivering
chills
joint_pain
stomach_pain
acidity
ulcers_on_tongue
muscle_wasting
vomiting
burning_micturition
spotting_ urination
fatigue
weight_gain
anxiety
cold_hands_and_feets
mood_swings
weight_loss
restlessness
lethargy
patches_in_throat
irregular_sugar_level
cough
high_fever
sunken_eyes
breathlessness
sweating
dehydration
indigestion
headache
yellowish_skin
dark_urine
nausea
loss_of_appetite
pain_behind_the_eyes
back_pain
constipation
abdominal_pain
diarrhoea
mild_fever
yellow_urine
yellowing_of_eyes
acute_liver_failure
fluid_overload
swelling_of_stomach
swelled_lymph_nodes
malaise
blurred_and_distorted_vision
phlegm
throat_irritation
redness_of_eyes
sinus_pressure
runny_nose
congestion
chest_pain
weakness_in_limbs
fast_heart_rate
pain_during_bowel_movements
pain_in_anal_region
bloody_stool
irritation_in_anus
neck_pain
dizziness
cramps
bruising
obesity
swollen_legs
swollen_blood_vessels
puffy_

In [120]:
# It looks like one or more of the symptoms are mispelled. Let's fix that!
df.rename(columns={'diarrhoea': 'diarrhea'}, inplace=True)
df.rename(columns={'spotting_ urination': 'spotty_urination'}, inplace=True)
df.rename(columns={'dischromic _patches': 'dischromic_patches'}, inplace=True)
df.rename(columns={'fluid_overload.1': 'fluid_overload'}, inplace=True)

column_names = df.columns.tolist()

# Test for effect
print("Column names in the dataset:")
for column_name in column_names:
    print(column_name)

Column names in the dataset:
itching
skin_rash
nodal_skin_eruptions
continuous_sneezing
shivering
chills
joint_pain
stomach_pain
acidity
ulcers_on_tongue
muscle_wasting
vomiting
burning_micturition
spotty_urination
fatigue
weight_gain
anxiety
cold_hands_and_feets
mood_swings
weight_loss
restlessness
lethargy
patches_in_throat
irregular_sugar_level
cough
high_fever
sunken_eyes
breathlessness
sweating
dehydration
indigestion
headache
yellowish_skin
dark_urine
nausea
loss_of_appetite
pain_behind_the_eyes
back_pain
constipation
abdominal_pain
diarrhea
mild_fever
yellow_urine
yellowing_of_eyes
acute_liver_failure
fluid_overload
swelling_of_stomach
swelled_lymph_nodes
malaise
blurred_and_distorted_vision
phlegm
throat_irritation
redness_of_eyes
sinus_pressure
runny_nose
congestion
chest_pain
weakness_in_limbs
fast_heart_rate
pain_during_bowel_movements
pain_in_anal_region
bloody_stool
irritation_in_anus
neck_pain
dizziness
cramps
bruising
obesity
swollen_legs
swollen_blood_vessels
puffy_face

In [121]:
# How many diseases are in the dataset?
# Back up the original dataset and copy a fresh one
df2 = df.copy()

# Remove duplicates in the "prognosis" column
unique_prognosis = df2['prognosis'].drop_duplicates()

# Count the number of unique diseases
num_unique_diseases = unique_prognosis.nunique()

print(f'The number of unique diseases in the "prognosis" column is: {num_unique_diseases}')

The number of unique diseases in the "prognosis" column is: 41


In [122]:
# Define features set
X = df.copy()
X.drop("prognosis", axis=1, inplace=True)
X.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                   0           0         0             0   
1                   0           0         0             0   
2                   0           0         0             0   
3                   0           0         0             0   
4                   0           0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   
2                    0                     0                   0        0   
3                    0                     0                   0        0   
4                    0                     0                   0        0   

   red_sore_around_nose  yellow_crust_ooze  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  

[5 rows x 132 columns]

In [123]:
# Define target vector
y = df["prognosis"].values.reshape(-1, 1)
y[:5]

array([['Fungal infection'],
       ['Fungal infection'],
       ['Fungal infection'],
       ['Fungal infection'],
       ['Fungal infection']], dtype=object)

In [124]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [125]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()

# Fitting the model
model = model.fit(X_train, y_train)

In [126]:
# Making predictions using the testing data
predictions = model.predict(X_test)

In [127]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Calculate the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Display the confusion matrix
print("Confusion Matrix:")
print(cm)

# Calculate the accuracy score
acc_score = accuracy_score(y_test, predictions)
print("Accuracy Score:", acc_score)

Confusion Matrix:
[[23  0  0 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 43  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 34]]
Accuracy Score: 1.0


In [128]:
# Displaying results
print("Confusion Matrix")
display(cm)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


array([[23,  0,  0, ...,  0,  0,  0],
       [ 0, 24,  0, ...,  0,  0,  0],
       [ 0,  0, 30, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 43,  0,  0],
       [ 0,  0,  0, ...,  0, 33,  0],
       [ 0,  0,  0, ...,  0,  0, 34]], dtype=int64)

Accuracy Score : 1.0
Classification Report
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        23
                                   AIDS       1.00      1.00      1.00        24
                                   Acne       1.00      1.00      1.00        30
                    Alcoholic hepatitis       1.00      1.00      1.00        24
                                Allergy       1.00      1.00      1.00        34
                              Arthritis       1.00      1.00      1.00        25
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        29
                            Chicken pox       1.00      1.00      1.00        25
                    Chronic cholestasis       1.00      1.00      1.00        32
                            Common Cold       1.00      1.00     

In [129]:
import h5py
import pickle
import base64

# Serialize the decision tree model to a string representation
model_str = pickle.dumps(model)
model_base64 = base64.b64encode(model_str)

# Save the base64-encoded model to an HDF5 file
with h5py.File('decision_tree_model.h5', 'w') as hf:
    hf.create_dataset('model', data=model_base64)

In [130]:
# The model is saved, now let's test it!

In [131]:
# Load the saved decision tree model from the HDF5 file
with h5py.File('decision_tree_model.h5', 'r') as hf:
    model_base64 = hf['model'][()]
    model_str = base64.b64decode(model_base64)
    loaded_model = pickle.loads(model_str)

In [132]:
# Load the testing data from the CSV file
testing_data = pd.read_csv('Testing.csv')

testing_data.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze            prognosis  
0                  0     Fungal infection  
1                  0              Allergy  
2                  0                 GERD  
3                  0  Chronic cholestasis  
4                  0        Drug Reaction  

[5 rows x 133 columns]

In [133]:
# Perform any necessary preprocessing steps on the testing data


In [134]:
# Get the list of column names
testing_column_names = testing_data.columns.tolist()

print("Column names in the dataset:")
for column_name in testing_column_names:
    print(column_name)

Column names in the dataset:
itching
skin_rash
nodal_skin_eruptions
continuous_sneezing
shivering
chills
joint_pain
stomach_pain
acidity
ulcers_on_tongue
muscle_wasting
vomiting
burning_micturition
spotting_ urination
fatigue
weight_gain
anxiety
cold_hands_and_feets
mood_swings
weight_loss
restlessness
lethargy
patches_in_throat
irregular_sugar_level
cough
high_fever
sunken_eyes
breathlessness
sweating
dehydration
indigestion
headache
yellowish_skin
dark_urine
nausea
loss_of_appetite
pain_behind_the_eyes
back_pain
constipation
abdominal_pain
diarrhoea
mild_fever
yellow_urine
yellowing_of_eyes
acute_liver_failure
fluid_overload
swelling_of_stomach
swelled_lymph_nodes
malaise
blurred_and_distorted_vision
phlegm
throat_irritation
redness_of_eyes
sinus_pressure
runny_nose
congestion
chest_pain
weakness_in_limbs
fast_heart_rate
pain_during_bowel_movements
pain_in_anal_region
bloody_stool
irritation_in_anus
neck_pain
dizziness
cramps
bruising
obesity
swollen_legs
swollen_blood_vessels
puffy_

In [135]:
# It looks like one or more of the symptoms are mispelled in the testing data. Let's fix that!
testing_data.rename(columns={'diarrhoea': 'diarrhea'}, inplace=True)
testing_data.rename(columns={'spotting_ urination': 'spotty_urination'}, inplace=True)
testing_data.rename(columns={'dischromic _patches': 'dischromic_patches'}, inplace=True)
testing_data.rename(columns={'fluid_overload.1': 'fluid_overload'}, inplace=True)

testing_column_names = testing_data.columns.tolist()

# Test for effect
print("Column names in the dataset:")
for column_name in testing_column_names:
    print(column_name)

Column names in the dataset:
itching
skin_rash
nodal_skin_eruptions
continuous_sneezing
shivering
chills
joint_pain
stomach_pain
acidity
ulcers_on_tongue
muscle_wasting
vomiting
burning_micturition
spotty_urination
fatigue
weight_gain
anxiety
cold_hands_and_feets
mood_swings
weight_loss
restlessness
lethargy
patches_in_throat
irregular_sugar_level
cough
high_fever
sunken_eyes
breathlessness
sweating
dehydration
indigestion
headache
yellowish_skin
dark_urine
nausea
loss_of_appetite
pain_behind_the_eyes
back_pain
constipation
abdominal_pain
diarrhea
mild_fever
yellow_urine
yellowing_of_eyes
acute_liver_failure
fluid_overload
swelling_of_stomach
swelled_lymph_nodes
malaise
blurred_and_distorted_vision
phlegm
throat_irritation
redness_of_eyes
sinus_pressure
runny_nose
congestion
chest_pain
weakness_in_limbs
fast_heart_rate
pain_during_bowel_movements
pain_in_anal_region
bloody_stool
irritation_in_anus
neck_pain
dizziness
cramps
bruising
obesity
swollen_legs
swollen_blood_vessels
puffy_face

In [136]:
# Extract the features from the testing data
new_X_test = testing_data.drop('prognosis', axis=1)

# Define target vector
new_y = testing_data["prognosis"].values.reshape(-1, 1)
new_y[:5]

# Fitting the model
model = model.fit(new_X_test,new_y )

# Make predictions using the loaded model
predictions = loaded_model.predict(new_X_test)


In [137]:
# Evaluate the model performance
# You can compare the predicted values with the actual target values in the testing dataset to evaluate the model performance
# Calculating the confusion matrix
cm2 = confusion_matrix(new_y, predictions)

# Display the confusion matrix
print("Confusion Matrix:")
print(cm)

# Calculate the accuracy score
acc_score = accuracy_score(new_y, predictions)
print("Accuracy Score:", acc_score)


Confusion Matrix:
[[23  0  0 ...  0  0  0]
 [ 0 24  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ... 43  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 34]]
Accuracy Score: 0.9761904761904762
